#lang info
(define collection "aoc2023")
(define deps '("base" "functional-lib" "megaparsack-lib"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
;; (define scribblings '(("scribblings/aoc2023.scrbl" ())))
(define pkg-desc "Description Here")
(define version "0.0")
(define pkg-authors '(yo))
(define license '(Apache-2.0 OR MIT))
(define test-omit-paths '("info.rkt"))
